# Generated by Django 4.0.3 on 2023-08-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
