# Generated by Django 4.0.3 on 2023-09-09 08:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, null=True, verbose_name='logo'),
        ),
    ]
